FDTMetadataBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: FDTMetadataBundle:Default:index }

FDTMetadataBundle_getLanguages:
    pattern:  /admin/{bundleName}/getLanguages
    defaults: { _controller: FDTMetadataBundle:getLanguages:index}

FDTMetadataBundle_getTipologie:
    pattern:  /admin/{bundleName}/{tipologia}/getTipologie
    defaults: { _controller: FDTMetadataBundle:getTipologie:index}

FDTMetadataBundle_updateTipologie:
    pattern:  /admin/{bundleName}/{tipologia}/manageTipologie/{id}
    defaults: { _controller: contenuti.manageTipologie:indexAction, id: false}