imports:
    - { resource: parameters.ini }
    - { resource: security.yml }
    
framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    

doctrine_mongodb:
    connections:
        default:
            server: mongodb://int-app-glusterfs.gemmyx.com:8080
            options:
                connect: true
    default_database: wilano
    document_managers:
        default:
            auto_mapping: true

stof_doctrine_extensions:
    default_locale: %locale%
    translation_fallback: true
    orm:
        default: ~
    mongodb:
        default:
          translatable : true
          sluggable: true
          timestampable: true


fdt_doctrine_ext: ~

fdt_admin:
    configuration:
      Tipologie:
        -
          name: id
          type: string
        -
          name: uniqueName
          type: string
        -
          name: uniqueSlug
          type: string
        -
          name: isActive
          type: boolean
          defaultValue: true
        -
          name: isPrivate
          type: boolean
          defaultValue: false
        -
          name: isConfigurable
          type: boolean
          defaultValue: false
        -
          name: hasPeriod
          type: boolean
          defaultValue: false
        -
          name: leaf
          type: boolean
          defaultValue: true
        -
          name: isNew
          type: boolean
          defaultValue: false
        -
          name: it_it-name
          type: string
        -
          name: en_us-name
          type: string
        
          
          
        
          
    menuConfig:
      metadata:
        -
          id: metadataContenuti
          text: Contenuti
          leaf: false
          action: open
          children:
            -
              id: metadataTipologieContenuti
              text: Tipologie
              leaf: false
              action: open
              children:
                -
                  id: metadataProdotti
                  text: Prodotti
                  leaf: true
                  tipologiaType: Prodotti
                  controller: Metadata.controller.Tipologie
                -
                  id: metadataSchede
                  text: Schede
                  leaf: true
                  tipologiaType: Schede
                  controller: Metadata.controller.Tipologie 
            

      parties:
        -
          id: Parties
          text: Parties
          leaf: true
          action: Parties.controller.Init
        -
          id: PartiesSettingsMenu
          text: Settings
          leaf: false
          action: open
          children:
            -
              id: PariesRoles
              text: Ruoli
              leaf: true
              action: Palla
      