fdt_admin:
    configuration:
        Options:
            document: Options
            campi:
                Traduzioni:
                    name:
                        name: name
                        type: string
                        text: Name
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                id:
                    name: id
                    type: string
                    text: id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                value:
                    name: value
                    type: string
                    text: Value
                    flex: 2
                    sortable: false
                    hidden: false,
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                ordine:
                    name: ordine
                    type: int
                    text: Ordine
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: numberfield
                    anchor: 20%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
        DataSet:
            document: DataSet
            associazioni:
                Options:
                    name: options
                    document: Options
                    type: hasMany
            campi:
                Traduzioni:
                    name:
                        name: name
                        type: string
                        text: Name
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                Search:
                    uniqueName:
                        name: uniqueName
                        type: string
                        text: Nome
                        operator: CN
                id:
                    name: id
                    type: string
                    text: id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                uniqueName:
                    name: uniqueName
                    type: string
                    text: Dataset
                    flex: 2
                    sortable: false
                    hidden: false,
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                uniqueSlug:
                    name: uniqueSlug
                    type: string
                    text: Unique Slug
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
        Attributo:
            document: Attributo
            campi:
                Traduzioni:
                    name:
                        name: name
                        type: string
                        text: Name
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                id:
                    name: id
                    type: string
                    text: id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                uniqueName:
                    name: uniqueName
                    type: string
                    text: Attributo
                    flex: 2
                    sortable: false
                    hidden: false,
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                    useForSearch: true
                uniqueSlug:
                    name: uniqueSlug
                    type: string
                    text: Unique Slug
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isActive:
                    name: isActive
                    type: boolean
                    defaultValue: true
                    text: Attivo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                tipo:
                    name: tipo
                    type: string
                    defaultValue: text
                    text: Tipo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Metadata.store.Attributi.Tipo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
        Config:
            document: Config
            campi:
                id:
                    name: id
                    type: string
                    text: Id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                uniqueName:
                    name: attributo.uniqueName
                    type: string
                    text: Attributo
                    flex: 1
                    sortable: false
                    hidden: false
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                relatedId:
                    name: relatedId
                    type: string
                    text: relatedId
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                ordine:
                    name: ordine
                    type: int
                    text: Ordine
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: numberfield
                    anchor: 20%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isActive:
                    name: isActive
                    type: boolean
                    defaultValue: true
                    text: Attivo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isObligatory:
                    name: isObligatory
                    type: boolean
                    defaultValue: true
                    text: Obbligatorio
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                inSearch:
                    name: inSearch
                    type: boolean
                    defaultValue: false
                    text: Per ricerche
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                hasTranslation:
                    name: hasTranslation
                    type: boolean
                    defaultValue: false
                    text: Ha Traduzione
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isPubblicable:
                    name: isPubblicable
                    type: boolean
                    defaultValue: true
                    text: Pubblicabile
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isForConfiguration:
                    name: isForConfiguration
                    type: boolean
                    defaultValue: false
                    text: Per configurazioni
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
        Tipologie:
            document: Tipologie
            campi:
                Traduzioni: 
                    name:
                        name: name
                        type: string
                        text: Name
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                    descrizione:
                        name: descrizione
                        type: string
                        text: Descrizione
                        fieldXtype: textareafield
                        allowBlank: true
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                id:
                    name: id
                    type: string
                    text: Id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                uniqueName:
                    name: uniqueName
                    type: string
                    xtype: treecolumn
                    text: Tipologia
                    flex: 2
                    sortable: false
                    hidden: false,
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                uniqueSlug:
                    name: uniqueSlug
                    type: string
                    text: Unique Slug
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isActive:
                    name: isActive
                    type: boolean
                    defaultValue: true
                    text: Attivo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isPrivate:
                    name: isPrivate
                    type: boolean
                    defaultValue: false
                    text: Privato
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isConfigurable:
                    name: isConfigurable
                    type: boolean
                    defaultValue: false
                    text: Configurabile
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                hasPeriod:
                    name: hasPeriod
                    type: boolean
                    defaultValue: false
                    text: Ha Periodo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                leaf:
                    name: leaf
                    type: boolean
                    defaultValue: true
                    useForColumn: false
                    useForModel: true
                    useForForm: false
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
                parentId:
                    name: parentId
                    type: string
                    defaultValue: null
                    useForColumn: false
                    useForModel: true
                    useForForm: false

    menuConfig:
        metadata:
            -
              id: metadataContenuti
              text: Contenuti
              leaf: false
              action: open
              children:
                -
                  id: metadataTipologieContenuti
                  text: Tipologie
                  leaf: false
                  action: open
                  children:
                    -
                      id: metadataProdotti
                      text: Prodotti
                      leaf: true
                      tipologiaType: Prodotti
                      controller: Metadata.controller.Tipologie
                    -
                      id: metadataSchede
                      text: Schede
                      leaf: true
                      tipologiaType: Schede
                      controller: Metadata.controller.Tipologie
            -
              id: metadataAttributi
              text: Gestione Attributi
              leaf: false
              action: open
              children:
                -
                  id: manageAttributi
                  text: Attributi
                  leaf: true
                  controller: Metadata.controller.Attributi
                -
                  id: manageDataset
                  text: Data set
                  leaf: true
                  controller: Metadata.controller.Dataset
                      
                      


        parties:
            -
              id: Parties
              text: Parties
              leaf: true
              action: Parties.controller.Init
            -
              id: PartiesSettingsMenu
              text: Settings
              leaf: false
              action: open
              children:
                -
                  id: PariesRoles
                  text: Ruoli
                  leaf: true
                  action: Palla