fdt_admin:
    configuration:
        Tipologie:
            fields:
                Traduzioni: 
                    name:
                        name: name
                        type: string
                        text: Name
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                    descrizione:
                        name: descrizione
                        type: string
                        text: Descrizione
                        fieldXtype: textareafield
                        allowBlank: true
                        useForColumn: true
                        useForModel: true
                        useForForm: true
                id:
                    name: id
                    type: string
                    text: Id
                    flex: 1
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: false
                uniqueName:
                    name: uniqueName
                    type: string
                    xtype: treecolumn
                    text: Tipologia
                    flex: 2
                    sortable: false
                    hidden: false,
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                uniqueSlug:
                    name: uniqueSlug
                    type: string
                    text: Unique Slug
                    sortable: false
                    hidden: true
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isActive:
                    name: isActive
                    type: boolean
                    defaultValue: true
                    text: Attivo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isPrivate:
                    name: isPrivate
                    type: boolean
                    defaultValue: false
                    text: Privato
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                isConfigurable:
                    name: isConfigurable
                    type: boolean
                    defaultValue: false
                    text: Configurabile
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                hasPeriod:
                    name: hasPeriod
                    type: boolean
                    defaultValue: false
                    text: Ha Periodo
                    flex: 1
                    sortable: false
                    hidden: false
                    fieldXtype: combo
                    store: Admin.store.SiNo
                    anchor: 40%
                    useForColumn: true
                    useForModel: true
                    useForForm: true
                leaf:
                    name: leaf
                    type: boolean
                    defaultValue: true
                    useForColumn: false
                    useForModel: true
                    useForForm: false
                isNew:
                    name: isNew
                    type: boolean
                    defaultValue: false
                    useForColumn: false
                    useForModel: true
                    useForForm: false
                parentId:
                    name: parentId
                    type: string
                    defaultValue: null
                    useForColumn: false
                    useForModel: true
                    useForForm: false

    menuConfig:
        metadata:
            -
              id: metadataContenuti
              text: Contenuti
              leaf: false
              action: open
              children:
                -
                  id: metadataTipologieContenuti
                  text: Tipologie
                  leaf: false
                  action: open
                  children:
                    -
                      id: metadataProdotti
                      text: Prodotti
                      leaf: true
                      tipologiaType: Prodotti
                      controller: Metadata.controller.Tipologie
                    -
                      id: metadataSchede
                      text: Schede
                      leaf: true
                      tipologiaType: Schede
                      controller: Metadata.controller.Tipologie 


        parties:
            -
              id: Parties
              text: Parties
              leaf: true
              action: Parties.controller.Init
            -
              id: PartiesSettingsMenu
              text: Settings
              leaf: false
              action: open
              children:
                -
                  id: PariesRoles
                  text: Ruoli
                  leaf: true
                  action: Palla